baseURL = "http://blog.alexchi.me/"
languageCode = "zh-cn"
theme = "kiera"

paginate = 3
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
#GoogleAnalytics = "abc"
DefaultContentLanguage = "zh"

[languages]
    [languages.zh]
        title = "Alex Chi的博客"
        tagline = "一位图形学爱好者的唠叨"
    [languages.en]
        title = "Alex Chi's Blog"
        tagline = "Chatter from a computer graphics fan"

[author]
    name = "Alex Chi的博客"
    #categories = "/categories"
    #tags = "/tags"
    user = "http://alexchi.me"
    github = "alexchicn"
    gitlab = "alexchicn"
    twitter = "alexchicn"
    email = "mailto:alexchicn@gmail.com"

[params]
    [params.favicon]
        #ico = "images/favicon.ico"  # path to a .ico to use as favicon
        png = "https://s.gravatar.com/avatar/acf66434234f9fa7785e80d79d880a54?s=80"

#[markup]
#    [markup.goldmark]
#        [markup.goldmark.renderer]
#            unsafe= true

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5
