baseURL = "http://blog.alexchi.me/"
languageCode = "zh-cn"
title = "Alex Chi的博客"
theme = "kiera"

paginate = 3
summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Alex Chi的博客"
    github = "alexchicn"
    gitlab = "alexchicn"
    twitter = "alexchicn"

[params]
    tagline = "一位图形学爱好者的唠叨"
    [params.favicon]
        #ico = "images/favicon.ico"  # path to a .ico to use as favicon
        png = "https://s.gravatar.com/avatar/acf66434234f9fa7785e80d79d880a54?s=80"
